
- name: 下载etcd二进制文件
  copy: src={{ base_dir }}/bin/{{ item }} dest=/usr/bin  mode=0755
  with_items:
  - etcd
  - etcdctl
  tags: upgrade_etd

 


- name: 分发证书相关
  synchronize: src={{ etcd_ssl_dir }}/{{ item }} dest={{ etcd_ssl_dir }}/{{ item }}
  with_items:
  - ca.pem
  - ca-key.pem
  - ca-config.json
  delegate_to: "{{ groups.deploy[0] }}"

- name: 创建etcd证书请求
  template: src=etcd-csr.json.j2 dest={{ etcd_ssl_dir }}/server-csr.json

- name: 创建 etcd证书和私钥
  shell: "cd {{ etcd_ssl_dir }}  && cfssl gencert \
        -ca={{ etcd_ssl_dir }}/ca.pem \
        -ca-key={{ etcd_ssl_dir }}/ca-key.pem \
        -config={{ etcd_ssl_dir }}/ca-config.json \
        -profile=etcd server-csr.json | cfssljson -bare server"

- name: 创建etcd的conf文件
  template: src=etcd.conf.j2 dest=/k8s/etcd/cfg/etcd.conf
  tags: upgrade_etcd

- name: 创建etcd的systemd unit文件
  template: src=etcd.service.j2 dest=/etc/systemd/system/etcd.service
  tags: upgrade_etcd

- name: 开机启用etcd服务
  shell: systemctl enable etcd
  ignore_errors: true

- name: 开启etcd服务
  shell: systemctl daemon-reload && systemctl restart etcd
  ignore_errors: true
  tags: upgrade_etcd

- name: 以轮询的方式等待服务同步完成
  shell: "systemctl status etcd.service|grep Active"
  register: etcd_status
  until: '"running" in etcd_status.stdout'
  retries: 8
  delay: 8
  tags: upgrade_etcd
