# # to create CA, kubeconfig, kube-proxy.kubeconfig etc. on 'deploy' node
- hosts: deploy
  roles:
  - deploy


# prepare tasks for all nodes
- hosts:
  - kube-master
  - kube-node
  roles:
  - prepare

- hosts:
  - keepalived
  roles:
  - keepalived
